# Generated by Django 4.1.7 on 2023-04-01 00:54
from typing import List
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления записи"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Имя", max_length=30, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Фамилия", max_length=30, verbose_name="Фамилия"
                    ),
                ),
                (
                    "about",
                    models.CharField(
                        help_text="Обо мне", max_length=255, verbose_name="Обо мне"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Адрес электронной почты",
                        max_length=50,
                        verbose_name="Email",
                    ),
                ),
                (
                    "github_link",
                    models.URLField(
                        help_text="Ссылка на GitHub", verbose_name="GitHub"
                    ),
                ),
                (
                    "resume_link",
                    models.URLField(
                        help_text="Ссылка на резюме", verbose_name="Резюме"
                    ),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
    ]
