# Generated by Django 4.1.7 on 2023-03-31 21:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default="",
                help_text="Подробное описание выполненной работы",
                verbose_name="Подробное описание",
            ),
        ),
    ]
